name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install Modules
        run: yarn

      - name: Test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run package
          yarn run lint
          yarn exec tsc
          yarn test
